# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destnation', models.CharField(max_length=255)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('plan', models.TextField()),
                ('favorite_travels', models.ManyToManyField(related_name='travels_joined', to='users.User')),
                ('travel_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels_created', to='users.User')),
            ],
        ),
    ]
