# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_book', '0006_auto_20171220_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
