# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('new_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite_courses',
            field=models.ManyToManyField(related_name='courses_liked', to='users.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to='users.User'),
        ),
    ]
