# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_book', '0003_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='login_registration_book.User'),
            preserve_default=False,
        ),
    ]
