# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coureses_created', to='users.User')),
            ],
        ),
    ]
